name: CI for Rust. 

on:
  push:
    branches:
      [main, master] 
  pull_request:
    branches:
      [main, master] 

jobs:
  build-test-lint:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Rust toolchain
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Step 3: Run `cargo build`
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      # Step 4: Run tests with `cargo test`
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      # Step 6: Check formatting with `cargo fmt`
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

